name: Create Veracode Users

on:
  workflow_dispatch:

jobs:
  create-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests veracode-api-signing

      - name: Create users
        env:
          VERACODE_API_KEY_ID:     ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
        run: python create_users.py
